services:
  postgres:
    image: postgres:16
    container_name: bers_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bers_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bers_network

volumes:
  postgres_data:

networks:
  bers_network:


